#pragma once
#include <stdint.h>
#include "../components/mlkem/clean512/api.h"

#if defined(PQCLEAN_MLKEM512_CLEAN_CRYPTO_ALGNAME)
    #define MLKEM_PUBLICKEYBYTES (PQCLEAN_MLKEM512_CLEAN_CRYPTO_PUBLICKEYBYTES)
    #define MLKEM_SECRETKEYBYTES (PQCLEAN_MLKEM512_CLEAN_CRYPTO_SECRETKEYBYTES)
    #define MLKEM_CIPHERTEXTBYTES (PQCLEAN_MLKEM512_CLEAN_CRYPTO_CIPHERTEXTBYTES)
    #define MLKEM_SHAREDSECRETBYTES (PQCLEAN_MLKEM512_CLEAN_CRYPTO_BYTES)
#elif defined(PQCLEAN_MLKEM768_CLEAN_CRYPTO_ALGNAME)
    #define MLKEM_PUBLICKEYBYTES (PQCLEAN_MLKEM768_CLEAN_CRYPTO_PUBLICKEYBYTES)
    #define MLKEM_SECRETKEYBYTES (PQCLEAN_MLKEM768_CLEAN_CRYPTO_SECRETKEYBYTES)
    #define MLKEM_CIPHERTEXTBYTES (PQCLEAN_MLKEM768_CLEAN_CRYPTO_CIPHERTEXTBYTES)
    #define MLKEM_SHAREDSECRETBYTES (PQCLEAN_MLKEM768_CLEAN_CRYPTO_BYTES)
#elif defined(PQCLEAN_MLKEM1024_CLEAN_CRYPTO_ALGNAME)
    #define MLKEM_PUBLICKEYBYTES (PQCLEAN_MLKEM1024_CLEAN_CRYPTO_PUBLICKEYBYTES)
    #define MLKEM_SECRETKEYBYTES (PQCLEAN_MLKEM1024_CLEAN_CRYPTO_SECRETKEYBYTES)
    #define MLKEM_CIPHERTEXTBYTES (PQCLEAN_MLKEM1024_CLEAN_CRYPTO_CIPHERTEXTBYTES)
    #define MLKEM_SHAREDSECRETBYTES (PQCLEAN_MLKEM1024_CLEAN_CRYPTO_BYTES)
#else
    #error "No ML-KEM variant defined"
#endif

#ifdef __cplusplus
extern "C" {
#endif

int mlkem_keypair(uint8_t *pk, uint8_t *sk);
int mlkem_enc(uint8_t *ct, uint8_t *ss, const uint8_t *pk);
int mlkem_dec(uint8_t *ss, const uint8_t *ct, const uint8_t *sk);

#ifdef __cplusplus
}
#endif