#ifndef MBEDTLS_CONFIG_H
#define MBEDTLS_CONFIG_H

#define MBEDTLS_BIGNUM_C
#define MBEDTLS_GENPRIME

#define MBEDTLS_OID_C
#define MBEDTLS_ASN1_PARSE_C
#define MBEDTLS_ASN1_WRITE_C

#define MBEDTLS_RSA_C
#define MBEDTLS_PKCS1_V15

#define MBEDTLS_MD_C
#define MBEDTLS_SHA256_C

#define MBEDTLS_PLATFORM_ZEROIZE_ALT

#endif /* MBEDTLS_CONFIG_H */
